name: "Setup Bootstrap"
description: "GitHub Action for scaffoldly/bootstrap"
inputs:
  action:
    description: "The action to run: 'plan` or 'apply'"
    required: true
  command:
    description: "The shell command to run with the 'sh' action"
    required: false
  repo-token:
    description: "The GitHub token for this repo. (https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-passing-github_token-as-an-input)"
    required: true
  root-email:
    description: "Root Email for your project (https://docs.scaffold.ly/getting-started/prerequisites#root-email)"
    required: true
  terraform-cloud-token:
    description: "Access Token to Terraform Cloud (https://docs.scaffold.ly/getting-started/prerequisites#terraform-cloud)"
    required: true
  dnt:
    description: "If set, opt-out of usage analytics"
outputs:
  organization:
    description: "The GitHub/Terraform Cloud Organization"
runs:
  using: "node12"
  main: "dist/index.js"
