name: "Setup Bootstrap"
description: "GitHub Action for scaffoldly/bootstrap"
inputs:
  action:
    description: "The action to run: 'plan` or 'apply', or 'terraform'"
    required: true
  terraform:
    description: "The arguments to send alongside the 'terraform' action"
    required: false
  repo-token:
    description: "The GitHub token for this repo. (https://docs.github.com/en/actions/reference/authentication-in-a-workflow#example-passing-github_token-as-an-input)"
    required: true
  root-email:
    description: "Root Email for your project (https://docs.scaffold.ly/getting-started/prerequisites#root-email)"
    required: true
  terraform-cloud-token:
    description: "Access Token to Terraform Cloud (https://docs.scaffold.ly/getting-started/prerequisites#terraform-cloud)"
    required: true
  module-directory:
    description: "The subdirectory of a specific module to build"
    required: false
  dnt:
    description: "If set, opt-out of usage analytics"
    required: false
outputs:
  organization:
    description: "The GitHub/Terraform Cloud Organization"
  terraform-output:
    description: "Any Terraform Outputs, as stringify'd JSON"
  matrix:
    description: "If there's an output variable called 'github_matrix_include', the values will be provided in this output"
runs:
  using: "node12"
  main: "dist/index.js"
